# Generated by Django 6.0 on 2025-12-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('kilometraje', models.IntegerField()),
                ('puertas', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
