# Generated by Django 6.0 on 2025-12-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='puertas',
        ),
        migrations.AddField(
            model_name='auto',
            name='body',
            field=models.CharField(choices=[('SUV', 'SUV'), ('SEDAN', 'Sedán'), ('HATCHBACK', 'Hatchback'), ('PICKUP', 'Pickup'), ('COUPE', 'Coupé'), ('MINIVAN', 'Minivan')], default='Sedan', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto',
            name='color',
            field=models.CharField(default='Blanco', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto',
            name='combustible',
            field=models.CharField(choices=[('bencina', 'Bencina'), ('diesel', 'Diésel'), ('electrico', 'Eléctrico'), ('hibrido', 'Híbrido')], default='bencina', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto',
            name='motor',
            field=models.CharField(default='1.6 litros', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto',
            name='transmision',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática')], default='automatica', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auto',
            name='kilometraje',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='auto',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
    ]
