# Generated by Django 6.0 on 2025-12-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_remove_auto_puertas_auto_body_auto_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='autos/'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='motor',
            field=models.CharField(help_text='Ej: 1.6, 2.0 Turbo, V6 3.5', max_length=50),
        ),
    ]
